name: Create Log PRs

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  log_prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log PR details
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_BODY="${{ github.event.pull_request.body }}"
        PR_DATE=$(date -u)
        echo "## $PR_TITLE - $PR_DATE" >> pull_request_log.md
        echo "$PR_BODY" >> pull_request_log.md
        echo "" >> pull_request_log.md

    - name: Commit and push changes
      run: |
        git config pull.rebase false
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull origin main
        git add pull_request_log.md
        git commit -m "Log PR #${{ github.event.pull_request.number }}"
        git push origin HEAD:main
